Repository embroider-build/create-release-plan-setup, pull requests merged in 2023-12, with the labels that each got.

#31 don't create a new release plan PR when releasing
  .github/workflows/plan-release.yml
  plan-release-template.yml.ejs
Labels: enhancement

#34 add discovered default branch to plan-release CI
  bin/bin.test.js
  bin/release-plan-setup.js
  plan-release-template.yml.ejs
Labels: enhancement

#36 batch dependabot updates for minor or patch dev deps
  .github/dependabot.yml
Labels: internal

#44 Fix checking devDependencies on early projects with mostly empty package.json
  bin/release-plan-setup.js
Labels: bug

#46 update release-plan
  package.json
  pnpm-lock.yaml
Labels: internal
