Repository embroider-build/create-release-plan-setup, pull requests merged in 2024-02, with the labels that each got.

#60 match release-plan test for Changelog header
  bin/bin.test.js
  bin/release-plan-setup.js
  package.json
  pnpm-lock.yaml
Labels: bug

#67 add an editorconfig file
  .editorconfig
  plan-release-template.yml.ejs
  publish-template.yml.ejs
Labels: internal

#68 Update peter-evans/create-pull-request
  .github/workflows/plan-release.yml
  plan-release-template.yml.ejs
Labels: enhancement

#71 run create-release-plan-setup
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
Labels: enhancement

#74 Fix typo
  release-template.md
Labels: bug

#77 fix the branch used when a PR is labelled
  plan-release-template.yml.ejs
Labels: bug

#80 update release-plan
  package.json
  pnpm-lock.yaml
Labels: enhancement

#81 update pnpm/action-setup in template
  plan-release-template.yml.ejs
  publish-template.yml.ejs
Labels: dependencies

#82 run npm init release-plan-setup on this repo
  .github/workflows/plan-release.yml
  RELEASE.md
Labels: internal
