Repository embroider-build/create-release-plan-setup, pull requests merged in 2024-11, with the labels that each got.

#156 if you're using pnpm make sure to set cache
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  plan-release-template.yml.ejs
  publish-template.yml.ejs
Labels: enhancement

#157 add --provenance to publish by default
  .github/workflows/publish.yml
  publish-template.yml.ejs
Labels: enhancement

#159 fix provenance for pnpm
  .github/workflows/publish.yml
  publish-template.yml.ejs
Labels: bug

#161 add required permissions for provenance
  .github/workflows/publish.yml
  publish-template.yml.ejs
Labels: bug

#166 drop support for Node 16
  .github/workflows/nodejs.yml
  package.json
  pnpm-lock.yaml
Labels: breaking

#167 update peter-evans/create-pull-request action
  .github/workflows/plan-release.yml
  plan-release-template.yml.ejs
Labels: enhancement

#170 Minor formatting improvements
  .github/workflows/plan-release.yml
  plan-release-template.yml.ejs
  release-template.md
Labels: enhancement
