Repository embroider-build/create-release-plan-setup, pull requests merged in 2025-02, with the labels that each got.

#189 update vitest
  bin/bin.test.js
  package.json
  pnpm-lock.yaml
Labels: internal

#193 Update the publish template to make use of `paths` filtering in github workflows
  publish-template.yml.ejs
Labels: enhancement

#194 Update the Plan Release template to include the version for single packages in the PR title and in the commit message.
  plan-release-template.yml.ejs
Labels: enhancement

#90 Update readme
  README.md
Labels: documentation

#197 update the release-plan setup
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
Labels: internal
